### ISSUE TITLE
Recommend to filter illegal characters when writing files

### ISSUE THREAD

**Issue by HydrangeaPurple** [RMEx/scripts-externalizer#6]
scripts-externalizer.rb

  def write_script(s)
    eval_depth(s[1])
    name = s[1].strip
	# TODO filter illegal characters
	name=name.gsub(/\/|\\|:|\*|\?|"|<|>|\|/,"")
    path = @dir.join "/"
    name = add_script(path, name)
    FileTools.write(path + "/" + name + ".rb", s[2])
  end

**Comment by BilouMaster** [comment]
Indeed, we should add that at the start of the method `add_script` line 289... I'll do that if I have time and I don't forget 😅

**Comment by HydrangeaPurple** [comment]
😅
